[env:esp32s3]
platform = espressif32@6.9.0
board = esp32-s3-devkitc-1
framework = espidf
board_build.mcu = esp32s3
board_build.flash_size = 2MB
board_upload.flash_size = 2MB

monitor_speed = 115200

build_flags =
    -DCFG_TUD_AUDIO=1
    -DCFG_TUD_AUDIO_FUNC_1_DESC_LEN=TUD_AUDIO_MIC_ONE_CH_DESC_LEN
    -DCFG_TUD_AUDIO_FUNC_1_CTRL_BUF_SZ=64
    -DCFG_TUD_AUDIO_ENABLE_EP_IN=1
    -DCFG_TUD_AUDIO_FUNC_1_N_AS_INT=1
    -DCFG_TUD_AUDIO_FUNC_1_N_BYTES_PER_SAMPLE_TX=2
    -DCFG_TUD_AUDIO_FUNC_1_N_CHANNELS_TX=1
    -DCFG_TUD_AUDIO_FUNC_1_SAMPLE_RATE=48000
    -DCFG_TUD_AUDIO_EP_SZ_IN=96
    -DCFG_TUD_AUDIO_FUNC_1_EP_IN_SZ_MAX=96
    -DCFG_TUD_AUDIO_FUNC_1_EP_IN_SW_BUF_SZ=384
